name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: |
        1. step one...
        2. step two...
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - LibreWolf
        - Opera
        - Opera Gx
        - Edge
        - Internet
        - Chromium
        - Brave
        - Vivaldi
        - Safari
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
        If you use python enable logging by 
        ```python
        import logging
        logging.basicConfig(level=logging.DEBUG)
        ```
        If you use rust try enabling by setting environment variable 
        ```shell
        RUST_LOG=trace
        ```
        
      render: shell
