name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: |
        1. step one...
        2. step two...
    validations:
      required: true
  - type: dropdown
    id: Operation System
    attributes:
      label: What OS are you running?
      multiple: true
      options:
        - Windows
        - Linux
        - MacOS
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
        You can run the program from the command line with
        RUST_BACKTRACE=1 RUST_LOG=debug mobslide.exe
        
      render: shell
